kalliyanam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("", include("members.urls")),
    path('', include(('members.urls', 'members'), namespace='members'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "customer"

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    
    path('update_task/<str:pk>/', views.updateTask, name="update_task"),
    path('delete_task/<str:pk>/', views.deleteTask, name="delete_task"),

    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name="register"),

]

members/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True)
    amount = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Members(models.Model):
    f_name = models.CharField(max_length=200, null=True)
    l_name = models.CharField(max_length=200, null=True)
    username = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.username

members/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import *

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        # fields = '__all__'
        fields = ['name' , 'address', 'amount' , 'complete']

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import TaskForm, CreateUserForm


# Create your views here.
@login_required(login_url='members:login')
def dashboard(request):
    if request.user.is_authenticated:
        search_query = ''
        if request.GET.get('search_query'):
            search_query = request.GET.get('search_query')

        user = request.user
        tasks = Task.objects.filter(user = user, name__icontains=search_query)

        form = TaskForm()

        if request.method=='POST':
            form = TaskForm(request.POST)
            if form.is_valid():
                task = form.save(commit=False)
                task.user = user
                form.save()
            return redirect('/')

        context = {'tasks':tasks, 'form':form}
        return render(request, 'dashboard.html', context)

@login_required(login_url='members:login')
def updateTask(request, pk):
    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
        return redirect('/')

    context = {'update_form': form}
    return render(request, 'update_task.html', context)

@login_required(login_url='members:login')
def deleteTask(request, pk):
    item = Task.objects.get(id=pk)

    if request.method == 'POST':
        item.delete()
        return redirect('/')


def user_login(request):
    if request.user.is_authenticated:
        return redirect('members:dashboard')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('members:dashboard')
            else:
                messages.info(request, 'Username or Password is incorrect')

        return render(request, 'user_login.html')

def user_logout(request):
  if request.method == 'POST':
    auth.logout(request)
    messages.success(request, 'You are now logged out')
    return redirect('members:login')
  
def user_register(request):
    if request.user.is_authenticated:
        return redirect('members:dashboard')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for' + user)
                return redirect('members:login')
        context = {'form':form}
        return render(request, 'user_register.html', context=context)
    

templates/update_task.html
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,700;1,800;1,900&display=swap');
    :root {
  --input-border: #8b8a8b;
  --input-focus-h: 245;
  --input-focus-s: 100%;
  --input-focus-l: 42%;
}

.form-control {
  font-size: 16px;
  font-size: max(16px, 1em);
  font-family: inherit;
  padding: 0.25em 0.5em;
  background-color: #fff;
  border: 2px solid var(--input-border);
  border-radius: 44px;
}
body{
        background-color: #212038 !important;
        display: flex;
        position: relative;
        font-family: Poppins,sans-serif;
        align-items: center;
        justify-content: center;
      }
      .update-form{
        background-color: #fff;
        padding: 30px 20px;
        width: 20%;
        display: flex;
        align-items: center;
        position: relative;
        justify-content: center;
        flex-direction: column;
      }
      h3{
        color: #212038;
        font-size: 1.6rem;
      }
      .input-group{
        margin: 10px 0;
        width: 100%;
      }
      body input{
        width: 100%;
      }
      .textbox{
        position: absolute;
        right: 25px;
        display: inline-flex;
        bottom: 28px;
        width: 20px;
      }
</style>



<form method="POST" action="" class="update-form">
    <h3>Update contact</h3>
    {% csrf_token %}
    <div class="input-group mb-3">

        {{update_form.name}}
    </div>
    <div class="input-group mb-2">
        {{update_form.address}}
    </div>
    <div class="input-group mb-2">
        {{update_form.amount}}
    </div>
    <div class="input-group mb-2 textbox">
        {{update_form.complete}}
    </div>

       <div class="d-flex justify-content-center mt-3 login_container">
         <input class="btn login_btn" type="submit" value="Update">
       </div>
</form>


<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field 
*/

//Query All input fields
var form_fields = document.getElementsByTagName('input')

for (var field in form_fields){	
form_fields[field].className += ' form-control'
}
</script>

templates/user_login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, user-scalable=no" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.1/font/bootstrap-icons.min.css" integrity="sha512-oAvZuuYVzkcTc2dH5z1ZJup5OmSQ000qlfRvuoTTiyTBjwX1faoyearj8KdMq0LgsBTHMrRuMek7s+CxF8yE+w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,700;1,800;1,900&display=swap');
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #ffffff !important;
		}
		.navbar-brand{
          font-family: 'Josefin Sans', sans-serif !important;
          color: #fff !important;
          font-weight: 400;
          font-size: 1.6rem;
        }
        .navbar{
          width: 90%;
          padding: 30px 20px;
          border-radius: 20px;
		  background-color: #272643;
          margin: 20px auto;
box-shadow:  20px 20px 60px #d5d5d5,
             -20px -20px 60px #ffffff;
        }
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #ffffff;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			/* box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); */
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			border-radius: 50px;
			background: #36355d !important;
			padding: 13px 25px;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #36355d !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			color: red;
			padding: 10px;
			margin-top: 10px;
		}
		.user_card{
			width: 31.25rem;
			height: 50vh;
			color: white;
			background-color: #272643;
		}
		@media screen and (min-width:767px){
          .navbar-brand span{
            display: unset;
          }
          .navbar-brand i{
            display: none;
          }
        }
        @media screen and (max-width:991px){
          .navbar-brand span{
            display: none;
          }
          .navbar-brand i{
            font-size: 2rem;
          }
		  body,
		  .container
		  {
        background-color: #212038 !important;
      }
      .container{
        padding: 40px 10px;
      }
		  .navbar{
			box-shadow: unset;
		  }
		  .user_card {
			margin-top: 20px;
			margin-bottom: 20px;
		}
        }
		@media screen and (max-width:500px){
          .navbar-brand{
            font-size: 1.2rem;
          }
        }
        @media screen and (max-width:991px){
			.navbar{
				width: 100%;
				margin: auto;
				border-radius: unset;
			}
        }
		footer{
          background-color: #272643;
        }
	</style>

</head>
<body>

	<nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand text-center" href="#">
			<svg id="logo-13" width="49" height="48" viewBox="0 0 49 48" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M1.98441 29.2899C1.98441 27.0299 2.42954 24.7919 3.29444 22.704C4.15935 20.6159 5.42701 18.7187 7.02513 17.1206C8.62324 15.5225 10.5204 14.2548 12.6084 13.3899C14.6965 12.5251 16.9344 12.0799 19.1945 12.0799V29.2899H1.98441Z" class="ccustom" fill="#442781"></path> <path d="M1.98441 29.2899C1.98441 31.55 2.42954 33.7879 3.29444 35.876C4.15935 37.964 5.42701 39.8612 7.02513 41.4593C8.62324 43.0574 10.5204 44.3251 12.6084 45.19C14.6965 46.0549 16.9344 46.5 19.1945 46.5V29.2899H1.98441Z" class="ccompli1" fill="#61459C"></path> <path d="M36.4043 29.2899C36.4043 31.55 35.9595 33.7879 35.0947 35.876C34.2298 37.964 32.9622 39.8612 31.3638 41.4593C29.7657 43.0574 27.8685 44.3251 25.7804 45.19C23.6925 46.0549 21.4545 46.5 19.1945 46.5V29.2899H36.4043Z" class="ccompli2" fill="#A992DB"></path> <path d="M47.0156 14.422C47.0156 21.5586 41.23 27.344 34.0935 27.344H21.1716V14.422C21.1716 7.2854 26.957 1.5 34.0935 1.5C41.23 1.5 47.0156 7.2854 47.0156 14.422Z" class="ccustom" fill="#FF7917"></path> </svg>
		  </a>

          </div>
        </div>
    </nav>


	<div class="container h-100">
		<div class="d-flex justify-content-center h-100 login-container">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 class="text-white" id="form-title">Login</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		
				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'members:register' %}" class="ml-2 text-white">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>

	<footer class="text-center text-white">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>
      
            <!-- Twitter -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-twitter"></i
            ></a>
      
            <!-- Google -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-google"></i
            ></a>
      
            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-instagram"></i
            ></a>
      
            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-linkedin-in"></i
            ></a>
      
            <!-- Github -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-github"></i
            ></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2023 Copyright: <br>
          <a class="text-white" href="https://WeddingGift.com/">Idea By - Ghanashyam</a><br>
          <a class="text-white" href="https://WeddingGift.com/">Front-End Developed - Sarvind Up</a><br>
          <a class="text-white" href="https://WeddingGift.com/">Back-End Developed - Sarathlal Srl</a>
        </div>
        <!-- Copyright -->
    </footer>

</body>

</html>

templates/user_register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.1/font/bootstrap-icons.min.css" integrity="sha512-oAvZuuYVzkcTc2dH5z1ZJup5OmSQ000qlfRvuoTTiyTBjwX1faoyearj8KdMq0LgsBTHMrRuMek7s+CxF8yE+w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<meta name="viewport" content="width=device-width, user-scalable=no" />
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,700;1,800;1,900&display=swap');

		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #fff !important;
			font-family: 'Poppins',sans-serif;
		}
		.navbar-brand{
          font-family: 'Josefin Sans', sans-serif !important;
          color: #fff !important;
          font-weight: 400;
          font-size: 1.6rem;
        }
        .navbar{
          width: 90%;
          padding: 30px 20px;
          border-radius: 20px;
		  background-color: #272643;
          margin: 20px auto;
box-shadow:  20px 20px 60px #d5d5d5,
             -20px -20px 60px #ffffff;
        }
		.user_card {
			width: 450px;
			height: 500px;
			margin-top: 20px;
			margin-bottom: 20px;
			background: #272643;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			/* box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); */
			border-radius: 5px;

		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			border-radius: 50px;
			height: 50px;
			background: #36355d !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #36355d !important;
			color: #fff !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		footer{
			background-color: #272643;
		}
		@media screen and (min-width:767px){
			.navbar{
				box-shadow: unset;
			}
          .navbar-brand span{
            display: unset;
          }
          .navbar-brand i{
            display: none;
          }
	}
        @media screen and (max-width:991px){
          .navbar-brand span{
            display: none;
          }
          .navbar-brand i{
            font-size: 2rem;
          }
		  body,
		  .container
		  {
        background-color: #212038 !important;
      }
		  .navbar{
			box-shadow: unset;
		  }
        }
		@media screen and (max-width:991px){
			.navbar{
				width: 100%;
				margin: auto;
				border-radius: unset;
			}
        }
	</style>

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-white">
        <div class="container-fluid">
			<a class="navbar-brand text-center" href="#">
				<svg id="logo-13" width="49" height="48" viewBox="0 0 49 48" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M1.98441 29.2899C1.98441 27.0299 2.42954 24.7919 3.29444 22.704C4.15935 20.6159 5.42701 18.7187 7.02513 17.1206C8.62324 15.5225 10.5204 14.2548 12.6084 13.3899C14.6965 12.5251 16.9344 12.0799 19.1945 12.0799V29.2899H1.98441Z" class="ccustom" fill="#442781"></path> <path d="M1.98441 29.2899C1.98441 31.55 2.42954 33.7879 3.29444 35.876C4.15935 37.964 5.42701 39.8612 7.02513 41.4593C8.62324 43.0574 10.5204 44.3251 12.6084 45.19C14.6965 46.0549 16.9344 46.5 19.1945 46.5V29.2899H1.98441Z" class="ccompli1" fill="#61459C"></path> <path d="M36.4043 29.2899C36.4043 31.55 35.9595 33.7879 35.0947 35.876C34.2298 37.964 32.9622 39.8612 31.3638 41.4593C29.7657 43.0574 27.8685 44.3251 25.7804 45.19C23.6925 46.0549 21.4545 46.5 19.1945 46.5V29.2899H36.4043Z" class="ccompli2" fill="#A992DB"></path> <path d="M47.0156 14.422C47.0156 21.5586 41.23 27.344 34.0935 27.344H21.1716V14.422C21.1716 7.2854 26.957 1.5 34.0935 1.5C41.23 1.5 47.0156 7.2854 47.0156 14.422Z" class="ccustom" fill="#FF7917"></path> </svg>
			</a>


          </div>
        </div>
    </nav>

    


	<div class="container h-100 register-body">
		<div class="d-flex user-form  justify-content-center h-100 w-full-sec">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 class="text-white my-3" id="form-title">Sign Up</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="" class="form">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register">
				   		</div>
					</form>
				</div>
                {{form.errors}}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links text-white">
						Already have an account? <a href="{% url 'members:login' %}" class="ml-2 text-white">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<footer class="text-center text-white">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>
      
            <!-- Twitter -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-twitter"></i
            ></a>
      
            <!-- Google -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-google"></i
            ></a>
      
            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-instagram"></i
            ></a>
      
            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-linkedin-in"></i
            ></a>
      
            <!-- Github -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-github"></i
            ></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2023 Copyright: <br>
          <a class="text-white" href="https://WeddingGift.com/">Idea By - Ghanashyam</a><br>
          <a class="text-white" href="https://WeddingGift.com/">Front-End Developed - Sarvind Up</a><br>
          <a class="text-white" href="https://WeddingGift.com/">Back-End Developed - Sarathlal Srl</a>
        </div>
        <!-- Copyright -->
    </footer>

	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>